import Head from "next/head";
import Navbar from "../components/Navbar";
import { createStyles } from "@mantine/core";
import HeroSection from "../components/HeroSection";
import FloatingIcons from "../components/FloatingIcons";
import ProjectsSection from "../components/ProjectsSection";
import SkillsetSection from "../components/SkillsetSection";
import ExperienceSection from "../components/ExperienceSection";
import Footer from "../components/Footer";

export default function Home() {
  const useStyles = createStyles((theme) => ({
    gradientWrapper: {
      backgroundImage:
        'url("images/damascus-dark.svg"), linear-gradient(69deg, rgba(19,17,28,1) 0%, rgba(47,15,42,1) 100%)',
    },
  }));

  const { classes, cx } = useStyles();

  return (
    <>
      <Head>
        <title>Atharane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{scrollBehavior: "smooth"}}>
        <FloatingIcons />
        <div className={classes.gradientWrapper}>
          <Navbar />
          <HeroSection />
        </div>
        <SkillsetSection />
        <ExperienceSection />
        <ProjectsSection />
        <Footer />
      </main>
    </>
  );
}
