import Head from "next/head";
import Navbar from "../components/Navbar";
import { createStyles } from "@mantine/core";
import HeroSection from "../components/HeroSection";
import CarousalSection from "../components/CarousalSection";
import ExpertiseSection from "../components/ExpertiseSection";
import ExperienceSection from "../components/ExperienceSection";
import Footer from "../components/Footer";

export default function Home() {
  const useStyles = createStyles((theme) => ({
    gradientWrapper: {
      background:
        "linear-gradient(69deg, rgba(19,17,28,1) 0%, rgba(47,15,42,1) 100%)",
    },
  }));

  const { classes, cx } = useStyles();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={classes.gradientWrapper}>
          <Navbar />
          <HeroSection />
        </div>
        <ExpertiseSection />
        <CarousalSection />
        <ExperienceSection />
        <Footer />
      </main>
    </>
  );
}
